version: "3.7"
services:
  tidal:
    build: .
    environment: 
      ENABLE_EXTRAMUROS: 0
    network_mode: "host"
    shm_size: '256mb'
    privileged: true
    ulimits:
        rtprio: 95
        memlock: -1
    user: tidal
    entrypoint: "bash -l"
    command: "./startup.sh"
    volumes:
        - "./configs/SuperCollider:/home/tidal/.config/SuperCollider:rw"
        - "/dev/shm:/dev/shm:rw"
    stdin_open: true
    tty: true
        
